### ISSUE TITLE
Simplify notbook missing

### ISSUE THREAD

**Issue by csaiedu** [rrtucci/mappa_mundi#4]
Hi

I am trying to work my way into MM, but the notebook indicated in https://github.com/rrtucci/mappa_mundi/blob/master/jupyter_notebooks/navigating_short_stories.ipynb

https://colab.research.google.com/drive/1S2EWOGkoCgjfOJzTRJ7PLeu4T8SBwhlF?usp=sharing
is non existent

Thank you

**Comment by rrtucci** [comment]
Hi,
It looks like that notebook was moved by its author, Anton, or maybe it was
a temporary file and google deleted it after it expired. However, there is
a copy of it among the jupyter notebooks in MM. Here is a partial
screenshot from the SUMMARY notebook explaining this. (the summary notebook
extracts the first cell of each notebook)
[image: image.png]

**Comment by csaiedu** [comment]
Thanks
